eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            default-zone: http://eureka:password@localhost:8761/eureka
            defaultZone: http://eureka:password@localhost:8761/eureka
            http: http//${eureka.instance.hostname}:${server.port}/eureka/
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        prefer-ip-address: false
    server:
        renewal-percent-threshold: 0.85



server:
    port: 8761
spring:
    application:
        name: eureka-server
    freemarker:
        prefer-file-system-access: false
        template-loader-path: classpath:/templates/
    security:
        user:
            name: eureka
            password: password
